"""Run one GenPRM-7B example through the pinned official implementation."""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path


DEFAULT_GENPRM_SRC = Path("/workspace/GenPRM/src")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--genprm-src", type=Path, default=DEFAULT_GENPRM_SRC)
    parser.add_argument("--model", default="GenPRM/GenPRM-7B")
    parser.add_argument("--tensor-parallel-size", type=int, default=1)
    parser.add_argument(
        "--allow-generated-code",
        action="store_true",
        help=(
            "Allow the official CodeExecutor to execute Python generated by "
            "the model. Use only inside an isolated disposable container."
        ),
    )
    return parser.parse_args()


def gpu_memory(torch_module: object) -> tuple[int, int]:
    free_bytes, total_bytes = torch_module.cuda.mem_get_info()
    used_mib = (total_bytes - free_bytes) // (1024 * 1024)
    total_mib = total_bytes // (1024 * 1024)
    return used_mib, total_mib


def main() -> None:
    args = parse_args()

    if not args.allow_generated_code:
        raise SystemExit(
            "Refusing to execute model-generated Python by default. Rerun "
            "inside an isolated disposable container with "
            "--allow-generated-code to reproduce the official path."
        )

    try:
        import torch
    except ModuleNotFoundError as error:
        raise SystemExit(
            "PyTorch is unavailable. Activate the GenPRM environment first: "
            "source /opt/genprm-env/bin/activate"
        ) from error
    if not (args.genprm_src / "prm_evaluation" / "genprm_inference.py").is_file():
        raise FileNotFoundError(
            f"Official GenPRM source not found under {args.genprm_src}. "
            "Run scripts/bootstrap_genprm_official.sh first."
        )
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA GPU is required for this smoke test.")

    sys.path.insert(0, str(args.genprm_src.resolve()))
    from prm_evaluation.genprm_inference import CodeExecutor, GenPRM

    messages = [
        {
            "role": "system",
            "content": (
                "You are a math teacher. Your task is to review and critique "
                "the paragraphs in solution step by step."
            ),
        },
        {
            "role": "user",
            "content": (
                "Question: What is the sum of the first 100 positive "
                "integers?\n\n"
                "First, use the formula for the sum of the first n positive "
                "integers, n(n+1)/2. Substituting n=100 gives "
                "100*101/2 = 5050."
            ),
        },
    ]

    print(f"Loading {args.model}...")
    load_start = time.perf_counter()
    genprm = GenPRM(
        args.model,
        tensor_parallel_size=args.tensor_parallel_size,
    )
    load_seconds = time.perf_counter() - load_start
    load_used, total = gpu_memory(torch)

    print(f"Model load time: {load_seconds:.2f} seconds")
    print(f"GPU memory after load (MiB): {load_used}, {total}")
    print("Running one official-inference path...")

    inference_start = time.perf_counter()
    output, reward = genprm.inference(
        messages,
        cur_step=1,
        code_executor=CodeExecutor(),
        execute=True,
        logging=False,
    )
    torch.cuda.synchronize()
    inference_seconds = time.perf_counter() - inference_start
    inference_used, total = gpu_memory(torch)

    print("\n===== SMOKE TEST RESULT =====")
    print(f"Inference time: {inference_seconds:.2f} seconds")
    print(f"GPU memory after inference (MiB): {inference_used}, {total}")
    print(f"Reward: {reward}")
    print("Output:")
    print(output[0])


if __name__ == "__main__":
    main()
